import { test, expect } from '@playwright/test';

test('mode toggle persists, advanced sweep excludes warmup, simple mode resets workload, history compares', async ({ page, request }) => {
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  await page.goto('/');
  const toggle = page.getByRole('switch', { name: 'Расширенный режим' });
  await expect(toggle).toHaveAttribute('aria-checked', 'false'); await toggle.click();
  await page.getByLabel('Название теста').fill('Расширенный sweep UI');
  await page.getByLabel('Всего запросов', { exact: true }).fill('2');
  await page.getByLabel('Параллельные запросы', { exact: true }).fill('2');
  await page.getByLabel('Макс. output токенов').fill('16');
  await page.getByLabel('Прогрев, запросов').fill('1');
  await page.getByLabel('Ступени параллельности').fill('1, 2');
  await page.getByRole('button', { name: 'Демо-тест', exact: true }).click();
  await expect(page.getByTestId('run-status')).toHaveText('Завершён');
  await expect(page.getByTestId('success-count')).toHaveText('4');
  await expect(page.getByRole('heading', { name: 'Подробные метрики', exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Ступени нагрузки', exact: true })).toBeVisible();
  let id = await page.evaluate(() => sessionStorage.getItem('burner-selected'));
  const advanced = await (await request.get(`/api/runs/${id}`)).json();
  expect(advanced.metrics.success).toBe(4); expect(advanced.warmupCompleted).toBe(2); expect(advanced.metrics.distributions.outputTokens.count).toBe(4);
  await page.reload(); await expect(toggle).toHaveAttribute('aria-checked', 'true');
  await expect(page.getByLabel('Прогрев, запросов')).toHaveValue('1');
  await toggle.click();
  await page.getByLabel('Название теста').fill('Простой после sweep UI');
  await page.getByRole('button', { name: 'Демо-тест', exact: true }).click();
  await expect(page.getByTestId('run-status')).toHaveText('Завершён');
  await expect(page.getByTestId('success-count')).toHaveText('2');
  await expect(page.getByRole('heading', { name: 'Подробные метрики', exact: true })).toHaveCount(0);
  id = await page.evaluate(() => sessionStorage.getItem('burner-selected'));
  const simple = await (await request.get(`/api/runs/${id}`)).json(); expect(simple.config.warmupRequests).toBe(0); expect(simple.config.sweepConcurrency).toEqual([]);
  await page.getByRole('button', { name: 'История', exact: true }).click();
  await page.getByRole('checkbox', { name: 'Сравнить Расширенный sweep UI', exact: true }).first().check();
  await page.getByRole('checkbox', { name: 'Сравнить Простой после sweep UI', exact: true }).first().check();
  await page.getByRole('button', { name: 'Сравнить (2/4)', exact: true }).click();
  await expect(page.getByRole('dialog', { name: 'Сравнение запусков' })).toBeVisible();
  await expect(page.getByRole('dialog').getByText('Прогрев', { exact: true })).toBeVisible();
  await page.keyboard.press('Escape'); await expect(page.getByRole('dialog')).toHaveCount(0);
  expect(errors).toEqual([]);
});

test('advanced configuration imports without key, exports settings and remains usable on mobile', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/'); await page.getByRole('switch', { name: 'Расширенный режим' }).click();
  const config = { name: 'Импорт конфигурации', endpoint: 'http://localhost:8000/v1', model: 'test-model', apiKey: 'never-import-this-key', prompt: 'hello', concurrency: 1, totalRequests: 3, maxTokens: 8, timeoutSeconds: 10, loadMode: 'rate', requestRate: 3, warmupRequests: 1, sloTtftMs: 500 };
  await page.getByLabel('Импорт конфигурации').setInputFiles({ name: 'config.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify({ config })) });
  await expect(page.getByLabel('Название теста')).toHaveValue(config.name);
  await expect(page.getByLabel('API-ключ')).toHaveValue('');
  await expect(page.getByLabel('Запросов в секунду')).toHaveValue('3');
  const downloadPromise = page.waitForEvent('download'); await page.getByRole('button', { name: 'Сохранить настройки' }).click();
  const download = await downloadPromise; const stream = await download.createReadStream(); const chunks = []; for await (const chunk of stream) chunks.push(chunk);
  const body = Buffer.concat(chunks).toString(); expect(body).not.toContain('apiKey'); expect(JSON.parse(body).config.warmupRequests).toBe(1);
  await page.getByRole('button', { name: 'Демо-тест', exact: true }).click();
  await expect(page.getByTestId('run-status')).toHaveText('Завершён');
  await expect(page.getByTestId('success-count')).toHaveText('3');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});
