import { Activity, ArrowDownToLine, ArrowUpRight, Check, ChevronDown, ChevronLeft, ChevronRight, CircleHelp, Clock3, FlaskConical, Gauge, Info, Play, RotateCcw, Square, Trash2, X } from 'lucide-react';
import { useState } from 'react';

export const number = (n, digits = 1) => n == null || !Number.isFinite(n) ? '—' : new Intl.NumberFormat('ru-RU', { maximumFractionDigits: digits }).format(n);
export const seconds = ms => ms == null ? '—' : `${number(ms / 1000, 2)} с`;
export const date = value => new Date(value).toLocaleString('ru-RU', { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit', second: '2-digit' });
export const statusNames = { running: 'Выполняется', stopping: 'Останавливается', completed: 'Завершён', cancelled: 'Остановлен', failed: 'Ошибка', interrupted: 'Прерван', success: 'Успешно', error: 'Ошибка' };
export const isRunning = run => ['running', 'stopping'].includes(run?.status);
export function Status({ status, testId }) { return <span data-testid={testId} className={`status ${status}`}><span className="status-dot" />{statusNames[status] || status}</span>; }
function Field({ label, hint, children, className = '' }) { return <label className={`field ${className}`}><span className="field-label">{label}{hint && <span className="field-hint">{hint}</span>}</span>{children}</label>; }

export function ConfigForm({ config, setConfig, start, busy, active, onDemo, advancedContent, onDiscoverModels, models = [], discovering, plannedRequests }) {
  const update = (key, value) => setConfig(c => ({ ...c, [key]: value }));
  const numeric = key => ({ value: config[key], onChange: e => update(key, e.target.value === '' ? '' : Number(e.target.value)) });
  return <form className="config-panel panel" onSubmit={e => { e.preventDefault(); start(false); }}>
    <div className="panel-heading"><h2><Gauge size={18} /> Параметры теста</h2><span className="small-muted">OpenAI API</span></div>
    <fieldset disabled={busy || active}>
      <div className="form-section">
        <Field label="Название теста" hint="необязательно"><input value={config.name} onChange={e => update('name', e.target.value)} placeholder="Например, Qwen · 8 параллельных" maxLength={100} /></Field>
        <Field label="Endpoint URL"><input type="url" required value={config.endpoint} onChange={e => update('endpoint', e.target.value)} placeholder="http://localhost:8000/v1" spellCheck={false} /></Field>
        <p className="field-note">Base URL или полный путь /chat/completions</p>
        <div className="form-row credentials">
          <Field label="Модель"><input required value={config.model} onChange={e => update('model', e.target.value)} placeholder="Qwen/Qwen3-8B" list="endpoint-models" spellCheck={false} maxLength={200} /></Field>
          <Field label="API-ключ"><input type="password" autoComplete="off" value={config.apiKey} onChange={e => update('apiKey', e.target.value)} placeholder="Необязательно" /></Field>
        </div>
        <div className="model-discovery"><datalist id="endpoint-models">{models.map(id => <option key={id} value={id} />)}</datalist><button className="text-link" type="button" disabled={discovering} onClick={onDiscoverModels}>{discovering ? 'Получаем модели…' : 'Загрузить список моделей'}</button>{models.length > 0 && <span>{models.length} доступно</span>}</div><p className="privacy-note"><Check size={12} /> Ключ не сохраняется в истории и на диске</p>
      </div>
      <div className="form-section">
        <div className="section-heading"><h3>Контекст запроса</h3><span className="small-muted">{number(config.prompt.length + config.system.length, 0)} символов</span></div>
        <Field label="Системный контекст" hint="system"><textarea rows={2} value={config.system} onChange={e => update('system', e.target.value)} placeholder="Инструкции и контекст для модели…" maxLength={500000} /></Field>
        <Field label="Текст запроса" hint="user"><textarea className="prompt-area" required rows={4} value={config.prompt} onChange={e => update('prompt', e.target.value)} maxLength={500000} /></Field>
        <p className="field-note">Одинаковый контекст отправляется в каждом запросе.</p>
      </div>
      <div className="form-section load-section">
        <div className="section-heading"><h3>Нагрузка</h3><span className="small-muted">Без автоматических повторов</span></div>
        <div className="form-row">
          <Field label="Параллельные запросы"><input type="number" required min="1" max="128" step="1" {...numeric('concurrency')} /></Field>
          <Field label="Всего запросов"><input type="number" required min={config.concurrency || 1} max="10000" step="1" {...numeric('totalRequests')} /></Field>
        </div>
        <div className="concurrency-presets" aria-label="Быстрый выбор параллельности">{[1, 4, 8, 16, 32].map(n => <button type="button" key={n} className={config.concurrency === n ? 'chosen' : ''} aria-pressed={config.concurrency === n} onClick={() => setConfig(c => ({ ...c, concurrency: n, totalRequests: Math.max(n, c.totalRequests) }))}>{n}</button>)}<span>одновременно</span></div>
        <div className="form-row">
          <Field label="Макс. output токенов"><input type="number" required min="1" max="131072" step="1" {...numeric('maxTokens')} /></Field>
          <Field label="Таймаут запроса, с"><input type="number" required min="1" max="3600" step="1" {...numeric('timeoutSeconds')} /></Field>
        </div>
        <details className="advanced"><summary>Совместимость API <ChevronDown size={14} /></summary><div className="advanced-body"><Field label="Параметр лимита токенов"><select value={config.tokenParameter} onChange={e => update('tokenParameter', e.target.value)}><option value="max_tokens">max_tokens</option><option value="max_completion_tokens">max_completion_tokens</option></select></Field><label className="checkbox"><input type="checkbox" checked={config.includeUsage} onChange={e => setConfig(c => ({ ...c, includeUsage: e.target.checked, ...(!e.target.checked ? { continuousUsage: false } : {}) }))} /> Запрашивать usage в потоке</label>{advancedContent && <label className="checkbox continuous-usage"><input type="checkbox" checked={!!config.continuousUsage} disabled={!config.includeUsage} onChange={e => update('continuousUsage', e.target.checked)} />Usage каждого чанка (если поддерживается)</label>}<p className="field-note">Отключите, если сервер не поддерживает stream_options. Без usage TPS недоступен.</p></div></details>
      </div>
      {advancedContent}
      <div className="form-footer"><button className="button primary start-button" type="submit"><Play size={16} fill="currentColor" />{busy ? 'Запускаем…' : active ? 'Тест выполняется' : 'Запустить тест'}<span> {config.concurrency || 0} ×</span></button><button className="button demo-button" type="button" onClick={e => { const fields = e.currentTarget.form.querySelectorAll('.advanced-settings input, .advanced-settings textarea, .advanced-settings select'); const invalid = [...fields].find(field => !field.checkValidity()); if (invalid) { const detail = invalid.closest('details'); if (detail) detail.open = true; invalid.reportValidity(); } else onDemo(); }}><FlaskConical size={15} />Демо-тест</button><p className="field-note centered">До {number((plannedRequests ?? config.totalRequests ?? 0) * (config.maxTokens || 0), 0)} output токенов за запуск</p></div>
    </fieldset>
  </form>;
}

function Metric({ title, value, unit, hint, accent, testId }) {
  return <div className={`metric ${accent ? 'metric-primary' : ''}`}><div className="metric-title">{title}<span title={hint} tabIndex="0" aria-label={hint}><CircleHelp size={13} /></span></div><div className="metric-value"><span data-testid={testId}>{value}</span><span className="metric-unit">{unit}</span></div><div className="metric-hint">{hint}</div></div>;
}

export function ThroughputChart({ run }) {
  const points = (run?.series || []).filter(p => p.throughput != null);
  const width = 720, height = 206, left = 42, right = 12, top = 16, bottom = 30;
  const maxX = Math.max(run?.elapsedMs || 0, 1000);
  const maxY = Math.max(...points.map(p => p.throughput), 10) * 1.2;
  const px = p => left + p.elapsedMs / maxX * (width - left - right);
  const py = p => top + (1 - p.throughput / maxY) * (height - top - bottom);
  const line = points.map((p, i) => `${i ? 'L' : 'M'}${px(p)},${py(p)}`).join(' ');
  const area = points.length ? `${line} L${px(points.at(-1))},${height - bottom} L${px(points[0])},${height - bottom} Z` : '';
  return <div className="chart-wrap"><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label="Накопленный throughput по завершённым запросам"><defs><linearGradient id="area-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#315bdd" stopOpacity="0.18" /><stop offset="100%" stopColor="#315bdd" stopOpacity="0.01" /></linearGradient></defs>{[0, 1, 2, 3, 4].map(i => { const y = top + i / 4 * (height - top - bottom); return <g key={i}><line x1={left} x2={width - right} y1={y} y2={y} stroke="#e9edf3" strokeDasharray="3 4" /><text x={left - 10} y={y + 4} textAnchor="end">{points.length ? number(maxY * (1 - i / 4), 0) : '—'}</text></g>; })}{[0, 1, 2, 3, 4].map(i => <text key={i} x={left + i / 4 * (width - left - right)} y={height - 5} textAnchor={i === 4 ? 'end' : i === 0 ? 'start' : 'middle'}>{number(maxX / 1000 * i / 4, 1)} с</text>)}{points.length > 0 && <><path d={area} fill="url(#area-fill)" /><path d={line} fill="none" stroke="#315bdd" strokeWidth="2.5" strokeLinejoin="round" />{points.length < 80 && points.map((p, i) => <circle key={i} cx={px(p)} cy={py(p)} r={points.length === 1 ? 4 : 2.5} fill="#315bdd"><title>{seconds(p.elapsedMs)}: {number(p.throughput)} tok/s</title></circle>)}</>}</svg>{points.length === 0 && <div className="chart-empty"><div className="empty-chart-icon"><Activity size={24} /></div><strong>{isRunning(run) ? 'Собираем первые результаты' : 'От первого токена до полной картины'}</strong><span>{run ? 'График появится после успешного ответа с usage' : 'Запустите тест, чтобы увидеть производительность'}</span></div>}</div>;
}

export function Results({ run, stop, repeat, page, setPage, stopping, advancedContent }) {
  const m = run?.metrics || {};
  const progress = run ? m.completed / (run.plannedRequests ?? run.config.totalRequests) * 100 : 0;
  return <div className="results-column">
    <section className="panel result-panel">
      <div className="panel-heading result-heading"><div><h2><Activity size={18} />{run ? run.name : 'Производительность'}</h2><p>{run ? `${date(run.startedAt)} · ${run.config.model}` : 'Все ключевые метрики в одном месте'}</p></div>{run ? <Status status={run.status} testId="run-status" /> : <span className="ready-label"><span />Готов к запуску</span>}</div>
      {run?.schemaVersion >= 2 && <div className="workload-summary"><span>{run.config.loadMode === 'rate' ? `${run.config.requestRate} RPS · ${run.config.arrivalPattern === 'poisson' ? 'Пуассон' : 'равномерно'}` : 'Постоянная параллельность'}</span>{run.stages?.length > 1 && <span>Ступень {(run.currentStage ?? 0) + 1}/{run.stages.length}</span>}{run.warmupTotal > 0 && <span>{run.phase === 'warmup' ? 'Прогрев' : 'Прогрето'}: {run.warmupCompleted}/{run.warmupTotal}{run.warmupErrors > 0 ? ` · ошибок ${run.warmupErrors}` : ''}</span>}{run.config.durationSeconds > 0 && <span>До {run.config.durationSeconds} с / ступень</span>}</div>}
      {run?.config.demo && <div className="demo-notice"><FlaskConical size={14} /><strong>Синтетические данные</strong><span>Демо для проверки интерфейса</span></div>}
      <div className="metrics-grid"><Metric accent title="Общий throughput" value={number(m.throughput)} unit="tok/s" testId="throughput-value" hint="Output токены / время измерения без прогрева" /><Metric title="TPS одного запроса" value={number(m.requestTps)} unit="tok/s" hint="Средний TPS, включая ожидание ответа" /><Metric title="Первый токен" value={number(m.ttftMs, 0)} unit="мс" hint="Среднее время до первого токена" /><Metric title="Задержка p95" value={number(m.latencyP95Ms / 1000 || null, 2)} unit="с" hint="95% успешных ответов быстрее" /></div>
      <div className="chart-section"><div className="chart-heading"><h3>Пропускная способность</h3><span className="legend"><i />Накопленный throughput</span></div><ThroughputChart run={run} /><p className="chart-note">По завершённым запросам · токены из usage API</p></div>
      <div className="run-summary"><div><span>Успешно</span><strong className="success-text" data-testid="success-count">{m.success ?? '—'}</strong></div><div><span>Ошибки</span><strong className={m.errors ? 'error-text' : ''}>{m.errors ?? '—'}</strong></div><div><span>Output токены</span><strong>{run ? number(m.outputTokens, 0) : '—'}{m.success > m.usageCount && <small> известно</small>}</strong></div><div><span>Время теста</span><strong>{run ? seconds(m.elapsedMs) : '—'}</strong></div><div><span>Запросов / с</span><strong>{number(m.requestsPerSecond, 2)}</strong></div></div>
      {run && <div className="progress-section"><div className="progress-meta"><span><strong>{m.completed}</strong> из {run.plannedRequests ?? run.config.totalRequests} запросов{isRunning(run) && ` · ${run.activeRequests} выполняются`}</span><span>{number(progress, 0)}%</span></div><div className="progress-track"><div style={{ width: `${progress}%` }} /></div>{m.success > m.usageCount && <p className="usage-warning"><Info size={14} />Usage получен для {m.usageCount} из {m.success} ответов. Общий TPS недоступен.</p>}{run.status === 'interrupted' && <p className="usage-warning">Сервер был выключен во время теста. Сохранены завершённые запросы.</p>}<div className="run-actions">{isRunning(run) ? <button className="button stop-button" disabled={stopping || run.status === 'stopping'} onClick={stop}><Square size={13} fill="currentColor" />Остановить тест</button> : <button className="button" onClick={repeat}><RotateCcw size={14} />Повторить параметры</button>}<span className="export-label"><ArrowDownToLine size={14} />Экспорт</span><a className="text-link" href={`/api/runs/${run.id}/export?format=json`} download>JSON</a><a className="text-link" href={`/api/runs/${run.id}/export?format=csv`} download>CSV</a></div></div>}
    </section>
    {advancedContent}
    {run && <details className="panel saved-config"><summary>Параметры этого замера <ChevronDown size={15} /></summary><div className="saved-config-body"><dl><div><dt>Endpoint</dt><dd>{run.config.demo ? 'Встроенный демо-провайдер' : run.config.endpoint}</dd></div><div><dt>Параллельность</dt><dd>{run.config.concurrency}</dd></div><div><dt>Лимит ответа</dt><dd>{number(run.config.maxTokens, 0)} токенов · {run.config.tokenParameter}</dd></div><div><dt>Таймаут</dt><dd>{run.config.timeoutSeconds} с</dd></div><div><dt>Usage в потоке</dt><dd>{run.config.includeUsage ? 'Запрашивается' : 'Не запрашивается'}</dd></div></dl>{run.config.system && <><h3>Системный контекст</h3><pre>{run.config.system}</pre></>}<h3>Текст запроса</h3><pre>{run.config.prompt}</pre></div></details>}
    <section className="panel requests-panel"><div className="panel-heading"><h2>Запросы <span className="count-pill">{run?.resultsTotal ?? m.completed ?? 0}</span></h2><span className="small-muted">Каждый ответ отдельно</span></div>{!run?.results?.length ? <div className="empty-requests"><div className="request-lines"><span /><span /><span /></div><p>{isRunning(run) ? 'Запросы выполняются' : 'Здесь будут результаты запросов'}</p><span>Статус, токены и время ответа для каждого запроса</span></div> : <><div className="table-scroll"><table><thead><tr><th>Запрос</th><th>Статус / этап</th><th>Токены</th><th>TTFT</th><th>Время</th><th>TPS <span title="Output токены / полное время запроса">ⓘ</span></th></tr></thead><tbody>{run.results.map(r => <tr key={r.index}><td className="request-index">#{String(r.index + 1).padStart(3, '0')}</td><td><Status status={r.status} />{r.phase === 'warmup' && <span className="request-phase">Прогрев</span>}{run.stages?.length > 1 && <span className="request-phase">Ступень {(r.stageIndex ?? 0) + 1}</span>}{r.error && <div className="request-error">{r.error}</div>}</td><td>{number(r.outputTokens, 0)}</td><td>{r.ttftMs == null ? '—' : `${number(r.ttftMs, 0)} мс`}</td><td>{seconds(r.durationMs)}</td><td>{r.status === 'success' && r.outputTokens != null ? number(r.outputTokens / (r.durationMs / 1000)) : '—'}</td></tr>)}</tbody></table></div>{(run.resultsTotal > 100 || page > 0) && <div className="pagination"><span>{page * 100 + 1}–{page * 100 + run.results.length} из {run.resultsTotal}</span><button className="icon-button" aria-label="Предыдущие запросы" disabled={page === 0} onClick={() => setPage(p => p - 1)}><ChevronLeft size={16} /></button><button className="icon-button" aria-label="Следующие запросы" disabled={(page + 1) * 100 >= run.resultsTotal} onClick={() => setPage(p => p + 1)}><ChevronRight size={16} /></button></div>}</>}</section>
    {!run && <div className="method-note"><Info size={17} /><p><strong>Измеряем, а не угадываем.</strong> Количество токенов берём из ответа API. Параллельность поддерживается на протяжении теста, пока в очереди есть запросы.</p></div>}
  </div>;
}

export function History({ runs, openRun, deleteRun, more, loadMore, compareIds = [], toggleCompare, onCompare, comparing }) {
  const [query, setQuery] = useState(''); const [confirmId, setConfirmId] = useState(null);
  const filtered = runs.filter(r => `${r.name} ${r.config.model} ${r.config.endpoint}`.toLowerCase().includes(query.toLowerCase()));
  return <section className="panel history-panel"><div className="panel-heading"><div><h2>История замеров <span className="count-pill">{runs.length}</span></h2><p>Параметры и результаты сохраняются на этом компьютере</p></div><button className="button" disabled={compareIds.length < 2 || comparing} onClick={onCompare}>Сравнить ({compareIds.length}/4)</button><input className="history-search" placeholder="Найти тест или модель…" aria-label="Поиск по истории" value={query} onChange={e => setQuery(e.target.value)} /></div>{!filtered.length ? <div className="history-empty"><Clock3 size={32} /><h3>{runs.length ? 'Ничего не найдено' : 'Ваш первый тест — начало истории'}</h3><p>{runs.length ? 'Попробуйте другой запрос.' : 'После запуска здесь появятся дата, параметры и результаты замера.'}</p></div> : <div className="table-scroll"><table className="history-table"><thead><tr>{toggleCompare && <th aria-label="Выбор для сравнения" />}<th>Тест / модель</th><th>Дата и время</th><th>Нагрузка</th><th>Throughput</th><th>Статус</th><th aria-label="Действия" /></tr></thead><tbody>{filtered.map(r => <tr key={r.id}>{toggleCompare && <td className="compare-select"><input type="checkbox" aria-label={`Сравнить ${r.name}`} checked={compareIds.includes(r.id)} disabled={!compareIds.includes(r.id) && compareIds.length >= 4} onChange={() => toggleCompare(r.id)} /></td>}<td><button className="history-open" onClick={() => openRun(r.id)}>{r.name}<ArrowUpRight size={14} /></button><div className="history-model">{r.config.demo && <FlaskConical size={12} />}{r.config.model}</div></td><td className="date-cell">{date(r.startedAt)}</td><td><strong>{r.config.concurrency} ×</strong><span className="history-detail">{r.config.totalRequests} запросов</span></td><td><strong>{number(r.metrics?.throughput)}</strong> <span className="small-muted">tok/s</span></td><td><Status status={r.status} />{!!r.metrics?.errors && <span className="history-detail error-text">Ошибок: {r.metrics.errors}</span>}</td><td>{!isRunning(r) && (confirmId === r.id ? <div className="delete-confirm"><button className="text-link error-text" onClick={() => { deleteRun(r.id); setConfirmId(null); }}>Удалить</button><button className="icon-button" aria-label="Отменить удаление" onClick={() => setConfirmId(null)}><X size={14} /></button></div> : <button className="icon-button" aria-label={`Удалить ${r.name}`} onClick={() => setConfirmId(r.id)}><Trash2 size={15} /></button>)}</td></tr>)}</tbody></table></div>}{more && <div className="load-more"><button className="button" onClick={loadMore}>Загрузить ещё</button></div>}</section>;
}

export function Help({ close }) {
  return <div className="modal-backdrop" onClick={close}><section className="help-modal panel" role="dialog" aria-modal="true" aria-label="Как читать результаты" onClick={e => e.stopPropagation()}><div className="panel-heading"><h2>Как читать результаты</h2><button className="icon-button" autoFocus onClick={close} aria-label="Закрыть справку"><X size={18} /></button></div><div className="help-content"><p><strong>Общий throughput</strong> — сумма output токенов успешных ответов, делённая на время теста. Показывает совокупную производительность при заданной параллельности.</p><p><strong>TPS одного запроса</strong> — среднее от токенов / полного времени каждого успешного запроса. Включает ожидание первого токена (end-to-end), поэтому отличается от скорости декодирования.</p><p><strong>TTFT</strong> — время от отправки запроса до первого непустого content или reasoning delta. Один сетевой чанк может содержать несколько токенов.</p><p><strong>p95</strong> — 95-й перцентиль полного времени успешных ответов. Ошибки и отмены в перцентили не входят.</p><p>Токены берём только из <code>usage.completion_tokens</code>. Они могут включать reasoning tokens. Если usage нет хотя бы у одного успешного ответа, общий throughput не рассчитывается; средний TPS рассчитан только по ответам с usage.</p><p>В расширенном режиме доступны прогрев, набор запросов, ступени параллельности и заданный RPS. Прогрев сохраняется отдельно и не входит в измерения. Кэширование префикса может влиять на результат; уникальный префикс запроса уменьшает совпадение, но не гарантирует cache miss. Автоматических повторов нет.</p><p><strong>Расширенные метрики:</strong> TTFO — ожидание видимого текста, TTST — интервал первого и второго чанка. TPOT и decode TPS — оценки по времени генерации и usage. SLO задают пределы задержки; goodput учитывает только успешные запросы, выполнившие все заданные пределы.</p><p>Время показано в часовом поясе браузера: <strong>{Intl.DateTimeFormat().resolvedOptions().timeZone}</strong>. Демо-результаты синтетические и не измеряют реальную модель.</p></div></section></div>;
}
