import { Activity, ArrowDownToLine, ArrowUpRight, Check, ChevronDown, ChevronLeft, ChevronRight, CircleHelp, Clock3, FlaskConical, Gauge, Info, Play, RotateCcw, Square, Trash2, X } from 'lucide-react';
import { useEffect, useId, useRef, useState } from 'react';
import { HistoryInput } from './HistoryInput.jsx';

export const number = (n, digits = 1) => n == null || !Number.isFinite(n) ? '—' : new Intl.NumberFormat('en-US', { maximumFractionDigits: digits }).format(n);
export const seconds = ms => ms == null ? '—' : `${number(ms / 1000, 2)} s`;
export const date = value => new Date(value).toLocaleString('en-US', { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit', second: '2-digit' });
export const statusNames = { running: 'Running', stopping: 'Stopping', completed: 'Completed', cancelled: 'Cancelled', failed: 'Error', interrupted: 'Interrupted', success: 'Successful', error: 'Error' };
export const isRunning = run => ['running', 'stopping'].includes(run?.status);
export function runProgress(run) {
  if (!run) return { percent: 0, label: '' };
  const warming = run.phase === 'warmup';
  const completed = warming ? run.warmupCompleted ?? 0 : run.metrics?.completed ?? 0;
  if (run.config.testMode === 'stress' && !warming) {
    const target = run.config.durationSeconds * 1000;
    const elapsed = Math.min(run.elapsedMs || 0, target);
    return { percent: Math.min(100, elapsed / target * 100), label: `${seconds(elapsed)} / ${seconds(target)} · ${number(completed, 0)} requests completed${isRunning(run) ? ` · ${run.activeRequests ?? 0} active` : ''}` };
  }
  const total = warming ? run.warmupTotal : run.plannedRequests ?? run.config.totalRequests;
  return { percent: total > 0 ? Math.min(100, completed / total * 100) : 0, label: `${number(completed, 0)} of ${number(total, 0)} ${warming ? 'warmup ' : ''}requests${isRunning(run) ? ` · ${run.activeRequests ?? 0} active` : ''}` };
}
export function Status({ status, testId }) { return <span data-testid={testId} className={`status ${status}`}><span className="status-dot" />{statusNames[status] || status}</span>; }
function Field({ label, hint, children, className = '' }) { return <label className={`field ${className}`}><span className="field-label">{label}{hint && <span className="field-hint">{hint}</span>}</span>{children}</label>; }

export function ConfigForm({ config, setConfig, start, busy, active, onDemo, advancedContent, onDiscoverModels, models = [], discovering, plannedRequests, collapsed = false, onToggleSettings, run, endpointSuggestions = [], modelSuggestions = [], rememberConnection, stress = false, stressDuration = 60, setStressDuration }) {
  const settingsId = useId();
  const warming = run?.phase === 'warmup';
  const { percent: completion, label: progressLabel } = runProgress(run);
  const customCurve = Boolean(!stress && advancedContent && config.loadCurve?.length);
  const curveConcurrency = customCurve && config.curveTarget !== 'rate';
  const update = (key, value) => setConfig(c => ({ ...c, [key]: value }));
  const numeric = key => ({ value: config[key], onChange: e => update(key, e.target.value === '' ? '' : Number(e.target.value)) });
  return <form className={`config-panel panel ${collapsed ? 'settings-collapsed' : ''}`} onSubmit={e => { e.preventDefault(); start(false); }}>
    <div className="panel-heading settings-heading"><h2><Gauge size={18} /> Test settings</h2><div className="settings-heading-actions"><span className="small-muted">OpenAI API</span><button type="button" className="settings-toggle" aria-expanded={!collapsed} aria-controls={settingsId} aria-label={collapsed ? 'Expand settings' : 'Collapse settings'} onClick={onToggleSettings}>{collapsed ? 'Expand settings' : 'Collapse settings'}<ChevronDown size={15} /></button></div></div>
    {collapsed && <div className="settings-compact"><div className="settings-compact-summary"><div><strong>{run?.name || config.name || 'Ready to configure'}</strong><span>{run?.config?.model || config.model || 'No model selected'} · {run?.config?.loadCurve?.length ? 'Custom load curve' : `${run?.config?.concurrency ?? config.concurrency} concurrent`}</span></div>{run && <div className="settings-compact-count"><strong>{isRunning(run) ? warming ? 'Warming up' : run.phase === 'draining' ? 'Finishing active requests' : 'Measuring' : 'Run summary'}</strong><span>{progressLabel}</span></div>}</div>{run && <div className="settings-progress" role="progressbar" aria-label="Settings run progress" aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.round(completion)} aria-valuetext={progressLabel}><span style={{ width: `${completion}%` }} /></div>}</div>}
    <fieldset id={settingsId} className="config-body" hidden={collapsed} disabled={busy || active}>
      <div className="form-section">
        <Field label="Test name" hint="optional"><input value={config.name} onChange={e => update('name', e.target.value)} placeholder="For example, Qwen · 8 concurrent" maxLength={100} /></Field>
        <HistoryInput label="Endpoint URL" type="url" required value={config.endpoint} onChange={value => update('endpoint', value)} onRemember={(value, commit) => rememberConnection('endpoint', value, commit)} suggestions={endpointSuggestions} dropdownLabel="Show saved endpoints" placeholder="http://localhost:8000/v1" spellCheck={false} maxLength={2048} />
        <p className="field-note">Base URL or full /chat/completions path</p>
        <div className="form-row credentials">
          <HistoryInput label="Model" required value={config.model} onChange={value => update('model', value)} onRemember={(value, commit) => rememberConnection('model', value, commit)} suggestions={modelSuggestions} dropdownLabel="Show saved models" placeholder="Qwen/Qwen3-8B" spellCheck={false} maxLength={200} />
          <Field label="API key"><input type="password" autoComplete="off" value={config.apiKey} onChange={e => update('apiKey', e.target.value)} placeholder="Optional" /></Field>
        </div>
        <div className="model-discovery"><button className="text-link" type="button" disabled={discovering} onClick={onDiscoverModels}>{discovering ? 'Loading models…' : 'Load model list'}</button>{models.length > 0 && <span>{models.length} available</span>}</div><p className="privacy-note"><Check size={12} /> API key stays in memory.</p>
      </div>
      <div className="form-section">
        <div className="section-heading"><h3>Request context</h3><span className="small-muted">{number(config.prompt.length + config.system.length, 0)} characters</span></div>
        <Field label="System context" hint="system"><textarea rows={2} value={config.system} onChange={e => update('system', e.target.value)} placeholder="Instructions and context for the model…" maxLength={500000} /></Field>
        <Field label="User prompt" hint="user"><textarea className="prompt-area" required rows={4} value={config.prompt} onChange={e => update('prompt', e.target.value)} maxLength={500000} /></Field>
        <p className="field-note">Sent with every request.</p>
      </div>
      <div className="form-section load-section">
        <div className="section-heading"><h3>Load</h3><span className="small-muted">No automatic retries</span></div>
        <div className="form-row">
          <Field label="Concurrent requests" hint={curveConcurrency ? 'set by curve' : customCurve ? 'RPS cap' : undefined}><input disabled={curveConcurrency} type="number" required min="1" max="128" step="1" {...numeric('concurrency')} /></Field>
          {stress ? <Field label="Load duration, s"><input type="number" required min="1" max="3600" step="1" value={stressDuration} onChange={e => setStressDuration(e.target.value === '' ? '' : Number(e.target.value))} /></Field> : <Field label="Total requests"><input type="number" required min={curveConcurrency ? 1 : config.concurrency || 1} max="10000" step="1" {...numeric('totalRequests')} /></Field>}
        </div>
        <div className="concurrency-presets" aria-label="Concurrency presets">{[1, 4, 8, 16, 32].map(n => <button type="button" disabled={curveConcurrency} key={n} className={config.concurrency === n ? 'chosen' : ''} aria-pressed={config.concurrency === n} onClick={() => setConfig(c => ({ ...c, concurrency: n, totalRequests: Math.max(n, c.totalRequests) }))}>{n}</button>)}<span>concurrent</span></div>
        <div className="form-row">
          <Field label="Max output tokens"><input type="number" required min="1" max="131072" step="1" {...numeric('maxTokens')} /></Field>
          <Field label="Request timeout, s"><input type="number" required min="1" max="3600" step="1" {...numeric('timeoutSeconds')} /></Field>
        </div>
        {stress && <p className="stress-note">No request-count limit. New requests stop after {stressDuration || 'the selected'} seconds; in-flight requests finish within their timeout. Warmup runs before the timer.</p>}<details className="advanced"><summary>API compatibility <ChevronDown size={14} /></summary><div className="advanced-body"><Field label="Token limit parameter"><select value={config.tokenParameter} onChange={e => update('tokenParameter', e.target.value)}><option value="max_tokens">max_tokens</option><option value="max_completion_tokens">max_completion_tokens</option></select></Field><label className="checkbox"><input type="checkbox" checked={config.includeUsage} onChange={e => setConfig(c => ({ ...c, includeUsage: e.target.checked, ...(!e.target.checked ? { continuousUsage: false } : {}) }))} /> Request streaming usage</label>{advancedContent && <label className="checkbox continuous-usage"><input type="checkbox" checked={!!config.continuousUsage} disabled={!config.includeUsage} onChange={e => update('continuousUsage', e.target.checked)} />Usage for every chunk (if supported)</label>}<p className="field-note">Disable if your server does not support stream_options. TPS requires usage data.</p></div></details>
      </div>
      {advancedContent}
      <div className="form-footer"><button className="button primary start-button" type="submit"><Play size={16} fill="currentColor" />{busy ? 'Starting…' : active ? 'Test running' : stress ? 'Start stress test' : 'Run test'}<span>{customCurve ? 'Curve' : `${config.concurrency || 0} ×`}</span></button><button className="button demo-button" type="button" onClick={e => { const fields = e.currentTarget.form.querySelectorAll('.advanced-settings input, .advanced-settings textarea, .advanced-settings select, .load-section input'); const invalid = [...fields].find(field => !field.checkValidity()); if (invalid) { const detail = invalid.closest('details'); if (detail) detail.open = true; invalid.reportValidity(); } else onDemo(); }}><FlaskConical size={15} />Demo test</button><p className="field-note centered">{stress ? `${stressDuration || '—'} s of load · no request-count limit` : `Up to ${number((plannedRequests ?? config.totalRequests ?? 0) * (config.maxTokens || 0), 0)} output tokens per run`}</p></div>
    </fieldset>
  </form>;
}

function Metric({ title, value, unit, hint, accent, testId }) {
  return <div className={`metric ${accent ? 'metric-primary' : ''}`}><div className="metric-title">{title}<span title={hint} tabIndex="0" aria-label={hint}><CircleHelp size={13} /></span></div><div className="metric-value"><span data-testid={testId}>{value}</span><span className="metric-unit">{unit}</span></div><div className="metric-hint">{hint}</div></div>;
}

export function ThroughputChart({ run }) {
  const chart = useRef(null);
  const [width, setWidth] = useState(720);
  useEffect(() => {
    const observer = new ResizeObserver(([entry]) => setWidth(Math.max(280, Math.round(entry.contentRect.width))));
    if (chart.current) observer.observe(chart.current);
    return () => observer.disconnect();
  }, []);
  const points = (run?.series || []).filter(p => p.throughput != null);
  const height = 230, left = 48, right = 16, top = 16, bottom = 32;
  const maxX = Math.max(run?.elapsedMs || 0, 1000);
  const maxY = Math.max(...points.map(p => p.throughput), 10) * 1.2;
  const px = p => left + p.elapsedMs / maxX * (width - left - right);
  const py = p => top + (1 - p.throughput / maxY) * (height - top - bottom);
  const line = points.map((p, i) => `${i ? 'L' : 'M'}${px(p)},${py(p)}`).join(' ');
  const area = points.length ? `${line} L${px(points.at(-1))},${height - bottom} L${px(points[0])},${height - bottom} Z` : '';
  return <div className="chart-wrap" ref={chart}><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label="Cumulative throughput from completed requests"><defs><linearGradient id="area-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="var(--accent)" stopOpacity="0.18" /><stop offset="100%" stopColor="var(--accent)" stopOpacity="0.01" /></linearGradient></defs>{[0, 1, 2, 3, 4].map(i => { const y = top + i / 4 * (height - top - bottom); return <g key={i}><line x1={left} x2={width - right} y1={y} y2={y} stroke="var(--border)" strokeDasharray="3 4" /><text x={left - 10} y={y + 4} textAnchor="end">{points.length ? number(maxY * (1 - i / 4), 0) : '—'}</text></g>; })}{[0, 1, 2, 3, 4].map(i => <text key={i} x={left + i / 4 * (width - left - right)} y={height - 5} textAnchor={i === 4 ? 'end' : i === 0 ? 'start' : 'middle'}>{number(maxX / 1000 * i / 4, 1)} s</text>)}{points.length > 0 && <><path d={area} fill="url(#area-fill)" /><path d={line} fill="none" stroke="var(--accent)" strokeWidth="2.5" strokeLinejoin="round" />{points.length < 80 && points.map((p, i) => <circle key={i} cx={px(p)} cy={py(p)} r={points.length === 1 ? 4 : 2.5} fill="var(--accent)"><title>{seconds(p.elapsedMs)}: {number(p.throughput)} tok/s</title></circle>)}</>}</svg>{points.length === 0 && <div className="chart-empty"><div className="empty-chart-icon"><Activity size={24} /></div><strong>{isRunning(run) ? 'Collecting the first results' : 'Waiting for a measurement'}</strong><span>{run ? 'The chart appears after a successful response with usage' : 'Configure your endpoint above, then run a test.'}</span></div>}</div>;
}

export function Results({ run, stop, repeat, page, setPage, stopping, advancedContent, onInspectRequest, progressInSettings }) {
  const m = run?.metrics || {};
  const { percent: progress, label: progressLabel } = runProgress(run);
  return <div className="results-column">
    <section className="panel result-panel">
      <div className="panel-heading result-heading"><div><h2><Activity size={18} />Performance</h2><p>{run ? `${run.name} · ${date(run.startedAt)} · ${run.config.model}` : 'Throughput and response latency'}</p></div>{run ? <Status status={run.status} testId="run-status" /> : <span className="ready-label"><span />Ready to run</span>}</div>
      {run?.schemaVersion >= 2 && <div className="workload-summary">{run.config.testMode === 'stress' && <span>Stress test · {run.config.durationSeconds} s · no request limit</span>}{run.phase === 'draining' && <span>Finishing active requests</span>}<span>{run.config.loadCurve?.length ? `Custom ${run.config.curveTarget === 'rate' ? 'RPS' : 'concurrency'} curve · ${run.config.curveInterpolation === 'step' ? 'step' : 'linear'}` : run.config.loadMode === 'rate' ? `${run.config.requestRate} RPS · ${run.config.arrivalPattern === 'poisson' ? 'Poisson' : 'constant'}` : 'Constant concurrency'}</span>{run.stages?.length > 1 && <span>Stage {(run.currentStage ?? 0) + 1}/{run.stages.length}</span>}{run.warmupTotal > 0 && <span>{run.phase === 'warmup' ? 'Warmup' : 'Warmed up'}: {run.warmupCompleted}/{run.warmupTotal}{run.warmupErrors > 0 ? ` · errors ${run.warmupErrors}` : ''}</span>}{run.config.testMode !== 'stress' && !run.config.loadCurve?.length && run.config.durationSeconds > 0 && <span>Up to {run.config.durationSeconds} s / stage</span>}</div>}
      {run?.config.demo && <div className="demo-notice"><FlaskConical size={14} /><strong>Synthetic data</strong><span>No endpoint requests are sent</span></div>}
      <div className="metrics-grid"><Metric accent title="Aggregate throughput" value={number(m.throughput)} unit="tok/s" testId="throughput-value" hint="Output tokens / measurement time, excluding warmup" /><Metric title="Per-request TPS" value={number(m.requestTps)} unit="tok/s" hint="Average TPS, including the wait for a response" /><Metric title="First token" value={number(m.ttftMs, 0)} unit="ms" hint="Average time to the first token" /><Metric title="Latency p95" value={number(m.latencyP95Ms / 1000 || null, 2)} unit="s" hint="95% of successful responses finish faster" /></div>
      <div className="chart-section"><div className="chart-heading"><h3>Throughput</h3><span className="legend"><i />Cumulative throughput</span></div><ThroughputChart run={run} /><p className="chart-note">Completed requests · tokens reported by the API</p></div>
      <div className="run-summary"><div><span>Successful</span><strong className="success-text" data-testid="success-count">{m.success ?? '—'}</strong></div><div><span>Errors</span><strong className={m.errors ? 'error-text' : ''}>{m.errors ?? '—'}</strong></div><div><span>Output tokens</span><strong>{run ? number(m.outputTokens, 0) : '—'}{m.success > m.usageCount && <small> reported</small>}</strong></div><div><span>Measurement time</span><strong>{run ? seconds(m.elapsedMs) : '—'}</strong></div><div><span>Requests / s</span><strong>{number(m.requestsPerSecond, 2)}</strong></div></div>
      {run && <div className="progress-section">{!progressInSettings && <><div className="progress-meta"><span>{progressLabel}</span><span>{number(progress, 0)}%</span></div><div className="progress-track"><div style={{ width: `${progress}%` }} /></div></>}{m.success > m.usageCount && <p className="usage-warning"><Info size={14} />Usage received for {m.usageCount} of {m.success} responses. Aggregate TPS is unavailable.</p>}{run.status === 'interrupted' && <p className="usage-warning">The server stopped during this run. Completed requests were saved.</p>}<div className="run-actions">{isRunning(run) ? <button className="button stop-button" disabled={stopping || run.status === 'stopping'} onClick={stop}><Square size={13} fill="currentColor" />Stop test</button> : <button className="button" onClick={repeat}><RotateCcw size={14} />Reuse settings</button>}<span className="export-label"><ArrowDownToLine size={14} />Export</span><a className="text-link" href={`/api/runs/${run.id}/export?format=json`} download>JSON</a><a className="text-link" href={`/api/runs/${run.id}/export?format=csv`} download>CSV</a></div></div>}
    </section>
    {advancedContent}
    {run && <details className="panel saved-config"><summary>Saved run settings <ChevronDown size={15} /></summary><div className="saved-config-body"><dl>{run.config.testMode === 'stress' && <div><dt>Stress duration</dt><dd>{run.config.durationSeconds} seconds · no request limit</dd></div>}<div><dt>Endpoint</dt><dd>{run.config.demo ? 'Built-in demo provider' : run.config.endpoint}</dd></div><div><dt>Concurrency</dt><dd>{run.config.concurrency}</dd></div><div><dt>Response limit</dt><dd>{number(run.config.maxTokens, 0)} tokens · {run.config.tokenParameter}</dd></div><div><dt>Timeout</dt><dd>{run.config.timeoutSeconds} s</dd></div><div><dt>Streaming usage</dt><dd>{run.config.includeUsage ? 'Requested' : 'Not requested'}</dd></div></dl>{run.config.system && <><h3>System context</h3><pre>{run.config.system}</pre></>}<h3>User prompt</h3><pre>{run.config.prompt}</pre></div></details>}
    <section className="panel requests-panel"><div className="panel-heading"><h2>Requests <span className="count-pill">{run?.resultsTotal ?? m.completed ?? 0}</span></h2><span className="small-muted">Select a request to inspect</span></div>{!run?.results?.length ? <div className="empty-requests"><div className="request-lines"><span /><span /><span /></div><p>{isRunning(run) ? 'Requests in progress' : 'Request results will appear here'}</p><span>Status, tokens, and latency for every request</span></div> : <><div className="table-scroll"><table><thead><tr><th>Request</th><th>Status / phase</th><th>Tokens</th><th>TTFT</th><th>Time</th><th>TPS <span title="Output tokens / total request time">ⓘ</span></th></tr></thead><tbody>{run.results.map(r => <tr key={r.index}><td className="request-index"><button type="button" className="request-inspect" aria-label={`View request ${r.index + 1}`} onClick={() => onInspectRequest?.(r)}>#{String(r.index + 1).padStart(3, '0')}<ArrowUpRight size={13} /></button></td><td><Status status={r.status} />{r.phase === 'warmup' && <span className="request-phase">Warmup</span>}{run.stages?.length > 1 && <span className="request-phase">Stage {(r.stageIndex ?? 0) + 1}</span>}{r.error && <div className="request-error">{r.error}</div>}</td><td>{number(r.outputTokens, 0)}</td><td>{r.ttftMs == null ? '—' : `${number(r.ttftMs, 0)} ms`}</td><td>{seconds(r.durationMs)}</td><td>{r.status === 'success' && r.outputTokens != null ? number(r.outputTokens / (r.durationMs / 1000)) : '—'}</td></tr>)}</tbody></table></div>{(run.resultsTotal > 100 || page > 0) && <div className="pagination"><span>{page * 100 + 1}–{page * 100 + run.results.length} of {run.resultsTotal}</span><button className="icon-button" aria-label="Previous requests" disabled={page === 0} onClick={() => setPage(p => p - 1)}><ChevronLeft size={16} /></button><button className="icon-button" aria-label="Next requests" disabled={(page + 1) * 100 >= run.resultsTotal} onClick={() => setPage(p => p + 1)}><ChevronRight size={16} /></button></div>}</>}</section>
    {!run && <div className="method-note"><Info size={17} /><p><strong>Measured at your endpoint.</strong> Token counts come from API usage. Concurrency is maintained while there are requests left to send.</p></div>}
  </div>;
}

export function History({ runs, openRun, deleteRun, more, loadMore, compareIds = [], toggleCompare, onCompare, comparing }) {
  const [query, setQuery] = useState(''); const [confirmId, setConfirmId] = useState(null);
  const filtered = runs.filter(r => `${r.name} ${r.config.model} ${r.config.endpoint}`.toLowerCase().includes(query.toLowerCase()));
  return <section className="panel history-panel"><div className="panel-heading"><div><h2>Run history <span className="count-pill">{runs.length}</span></h2><p>Settings and results are saved on this computer</p></div><button className="button" disabled={compareIds.length < 2 || comparing} onClick={onCompare}>Compare ({compareIds.length}/4)</button><input className="history-search" placeholder="Find a test or model…" aria-label="Search history" value={query} onChange={e => setQuery(e.target.value)} /></div>{!filtered.length ? <div className="history-empty"><Clock3 size={32} /><h3>{runs.length ? 'No matches' : 'Your first test starts your history'}</h3><p>{runs.length ? 'Try another search.' : 'Run a test to save its date, settings, and results here.'}</p></div> : <div className="table-scroll"><table className="history-table"><thead><tr>{toggleCompare && <th aria-label="Select for comparison" />}<th>Test / model</th><th>Date and time</th><th>Load</th><th>Throughput</th><th>Status</th><th aria-label="Actions" /></tr></thead><tbody>{filtered.map(r => <tr key={r.id}>{toggleCompare && <td className="compare-select"><input type="checkbox" aria-label={`Compare ${r.name}`} checked={compareIds.includes(r.id)} disabled={!compareIds.includes(r.id) && compareIds.length >= 4} onChange={() => toggleCompare(r.id)} /></td>}<td><button className="history-open" onClick={() => openRun(r.id)}>{r.name}<ArrowUpRight size={14} /></button><div className="history-model">{r.config.demo && <FlaskConical size={12} />}{r.config.model}</div></td><td className="date-cell">{date(r.startedAt)}</td><td><strong>{r.config.loadCurve?.length ? (r.config.curveTarget === 'rate' ? 'RPS curve' : 'Concurrency curve') : `${r.config.concurrency} ×`}</strong><span className="history-detail">{r.config.testMode === 'stress' ? `Stress · ${r.config.durationSeconds} s · ${r.metrics?.completed ?? 0} requests` : `${r.config.totalRequests} requests`}{r.config.loadCurve?.length ? ' · custom curve' : ''}</span></td><td><strong>{number(r.metrics?.throughput)}</strong> <span className="small-muted">tok/s</span></td><td><Status status={r.status} />{!!r.metrics?.errors && <span className="history-detail error-text">Errors: {r.metrics.errors}</span>}</td><td>{!isRunning(r) && (confirmId === r.id ? <div className="delete-confirm"><button className="text-link error-text" onClick={() => { deleteRun(r.id); setConfirmId(null); }}>Delete</button><button className="icon-button" aria-label="Cancel deletion" onClick={() => setConfirmId(null)}><X size={14} /></button></div> : <button className="icon-button" aria-label={`Delete ${r.name}`} onClick={() => setConfirmId(r.id)}><Trash2 size={15} /></button>)}</td></tr>)}</tbody></table></div>}{more && <div className="load-more"><button className="button" onClick={loadMore}>Load more</button></div>}</section>;
}

export function Help({ close }) {
  return <div className="modal-backdrop" onClick={close}><section className="help-modal panel" role="dialog" aria-modal="true" aria-label="Reading results" onClick={e => e.stopPropagation()}><div className="panel-heading"><h2>Reading results</h2><button className="icon-button" autoFocus onClick={close} aria-label="Close help"><X size={18} /></button></div><div className="help-content"><p><strong>Aggregate throughput</strong> is the sum of output tokens from successful responses divided by measurement time. It shows aggregate performance at the configured load.</p><p><strong>Per-request TPS</strong> averages tokens divided by the full duration of each successful request. It includes waiting for the first token, so it differs from decode speed.</p><p><strong>TTFT</strong> measures time from sending a request to the first nonempty content or reasoning delta. A network chunk may contain several tokens.</p><p><strong>p95</strong> is the 95th percentile of successful response times. Errors and cancellations are excluded.</p><p>Token counts come only from <code>usage.completion_tokens</code>. They may include reasoning tokens. Aggregate throughput is unavailable if any successful response lacks usage; average request TPS uses only responses with usage.</p><p>Advanced mode offers warmup, prompt datasets, concurrency sweeps, request rates, and custom load curves. Warmup is stored separately and excluded from measurements. Prefix caching can affect results; a unique request prefix reduces overlap but does not guarantee a cache miss. There are no automatic retries.</p><p><strong>Advanced metrics:</strong> TTFO measures time to visible text; TTST measures the gap between the first and second chunks. TPOT and decode TPS are estimates using generation time and usage. SLOs set latency limits; goodput counts successful requests that satisfy every enabled limit.</p><p>Times use your browser time zone: <strong>{Intl.DateTimeFormat().resolvedOptions().timeZone}</strong>. Demo results are synthetic and do not measure a real model.</p></div></section></div>;
}
